[WIP] agent: memif support
projectcalico/vpp-dataplane pull request #180
Opened 2021-05-10 17:49 UTC by sknat

Signed-off-by: Nathan Skrzypczak <nathan.skrzypczak@gmail.com>

2021-06-28 22:51 UTC, ivan4th commented on vpplink/types/memif.go
> +	MemifSlave  MemifRole = MemifRole(memif.MEMIF_ROLE_API_MASTER)
Should be ```MemifSlave  MemifRole = MemifRole(memif.MEMIF_ROLE_API_SLAVE)``` here

2021-07-19 17:47 UTC, sknat commented on vpplink/types/memif.go
> +	MemifSlave  MemifRole = MemifRole(memif.MEMIF_ROLE_API_MASTER)
Right 😄
Thanks for the proof-read !

2021-08-12 08:14 UTC, AloysAugustin requested changes

2021-08-12 08:14 UTC, AloysAugustin commented on calico-vpp-agent/cni/cni_server.go
> +		for k, v := range workload.Annotations {
Let's update the annotation format as discussed offline 🙂

2021-08-13 13:07 UTC, sknat commented on test/yaml/Makefile
> +%-image:
Right, will rename everything `calicovpp/test-*` and redo the pushes

2021-08-13 13:33 UTC, sknat reviewed
Everythings should be addressed, updates pushed to #207 as both PRs overlap more and more

2021-08-30 09:10 UTC, sknat commented
Closing in favor of #207

2021-08-30 09:10 UTC, closed without merging