Feature/add hostports
projectcalico/vpp-dataplane pull request #199
Opened 2021-06-24 16:58 UTC by hedibouattour

2021-07-09 09:32 UTC, AloysAugustin requested changes
Looks good but I think the cleanup part is missing in `DelVppInterface`.

2021-08-03 16:15 UTC, AloysAugustin reviewed
Looks good to me with the latest changes, @sknat could you review as well for the interaction with the cnat?

2021-08-04 14:21 UTC, sknat commented on calico-vpp-agent/cni/network_vpp.go
> +		s.BindHostPort(&podSpec.HostPorts[idx], podSpec.ContainerIps[0].IP)
We should also choose the first `podSpec.ContainerIps` that matches the ip version of `port.HostIP` in order to support dualstack (aka ipv4 + ipv6)

2021-08-04 14:23 UTC, sknat commented on calico-vpp-agent/cni/cni_server.go
> +			HostIP:        port.HostIp,
Maybe `net.ParseIP` here, to directly store the parsed `net.IP` ?

2021-08-10 08:32 UTC, sknat commented on calico-vpp-agent/cni/network_vpp.go
> +	for idx := range podSpec.HostPorts {
Here you might exceed the length of the table, and also we want to expose the ports on all the container addresses. 
Maybe you could use a dedicated function returning the first address that matches 
````golang
for _, hostPort := range podSpec.HostPorts {
   for _, containerAddr := range podSpec.ContainerIps {
       if addrFamilyDiffers (containerAddr, hostPort.HostIP) == nil {
          continue
       }
       err = s.BindHostPort(hostPort, containerAddr)
       ...
   } 
}
````
For the error cleanup, we might want to have `s.BindHostPort` return the EntryID and do `hostPorts.EntryID = id` here. That way if one of the call fails, we can call delete on all the previously created entries.

2021-08-10 08:32 UTC, sknat commented on calico-vpp-agent/cni/cni_server.go
> +		s.log.Errorf("Error re-injecting cnat entry %s : %v", entry.String(), err)
We could `return error.Wrapf(err, "...")`

2021-08-10 08:32 UTC, sknat commented on calico-vpp-agent/cni/storage/storage.go
> +	HostIP        net.IP
Maybe ```` `struc:"[16]byte"` ```` to avoid having `HostIPSize`

2021-08-16 09:12 UTC, AloysAugustin commented
Holding merge until the matching libcalico-go and cni-plugin PRs are merged so that we can refer to the upstream .proto in calico-vpp-agent/proto/Makefile .

2021-11-26 16:24 UTC, AloysAugustin approved these changes

2021-11-26 16:27 UTC, sknat approved these changes

2021-11-26 16:28 UTC, merged